import type { User } from "@/types/user";

export const mockUsers: User[] = [
    {
        id: '1',
        name: 'João Silva',
        email: 'joao.silva@example.com',
        profile: 'Admin',
        status: 'Ativo',
        createdAt: '2024-01-15T10:30:00Z',
    },
    {
        id: '2',
        name: 'Maria Santos',
        email: 'maria.santos@example.com',
        profile: 'Usuário',
        status: 'Ativo',
        createdAt: '2024-02-20T14:45:00Z',
    },
    {
        id: '3',
        name: 'Pedro Oliveira',
        email: 'pedro.oliveira@example.com',
        profile: 'Gerente',
        status: 'Ativo',
        createdAt: '2024-01-10T09:00:00Z',
    },
    {
        id: '4',
        name: 'Ana Costa',
        email: 'ana.costa@example.com',
        profile: 'Usuário',
        status: 'Inativo',
        createdAt: '2023-12-05T16:20:00Z',
    },
    {
        id: '5',
        name: 'Carlos Ferreira',
        email: 'carlos.ferreira@example.com',
        profile: 'Admin',
        status: 'Ativo',
        createdAt: '2024-03-01T11:15:00Z',
    },
    {
        id: '6',
        name: 'Beatriz Lima',
        email: 'beatriz.lima@example.com',
        profile: 'Gerente',
        status: 'Ativo',
        createdAt: '2024-02-14T08:30:00Z',
    },
    {
        id: '7',
        name: 'Ricardo Souza',
        email: 'ricardo.souza@example.com',
        profile: 'Usuário',
        status: 'Inativo',
        createdAt: '2023-11-20T13:45:00Z',
    },
    {
        id: '8',
        name: 'Fernanda Alves',
        email: 'fernanda.alves@example.com',
        profile: 'Usuário',
        status: 'Ativo',
        createdAt: '2024-01-25T15:00:00Z',
    },
    {
        id: '9',
        name: 'Lucas Rodrigues',
        email: 'lucas.rodrigues@example.com',
        profile: 'Gerente',
        status: 'Ativo',
        createdAt: '2024-02-10T10:00:00Z',
    },
    {
        id: '10',
        name: 'Juliana Martins',
        email: 'juliana.martins@example.com',
        profile: 'Usuário',
        status: 'Ativo',
        createdAt: '2024-03-05T12:30:00Z',
    },
    {
        id: '11',
        name: 'Roberto Pereira',
        email: 'roberto.pereira@example.com',
        profile: 'Admin',
        status: 'Inativo',
        createdAt: '2023-10-15T09:15:00Z',
    },
    {
        id: '12',
        name: 'Patricia Gomes',
        email: 'patricia.gomes@example.com',
        profile: 'Usuário',
        status: 'Ativo',
        createdAt: '2024-01-30T14:20:00Z',
    },
];
